# Generated by Django 4.2.14 on 2024-08-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_season_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
